### ISSUE TITLE
Can we use this for sensitivity?

### ISSUE THREAD

**Issue by owopeachy** [oleg-st/InvertMouse#4] opened 2022-11-04 09:25 UTC
Could we add the ability to switch between active interception profiles with this program as well? If we can make this switch profiles in the same way it switches y axis, we can make 2 profiles, one normal and one that offsets the shitty 4.44:1 x/y ratio and the inverted mouse acceleration issues this game has, letting us have normal camera operation and still keeping normal mouse operation in menus

EDIT: alright i misunderstood how interception works, the profiles i was talking about was from another separate program, so ignore that, still, a way to set 2 sensitivity/acceleration profiles that switch like the x/y axis with the cursor would be stellar and really make this an all in one genshin mouse fix

**Comment by oleg-st** [comment] 2022-11-04 13:12
I can add custom multipliers to the inverted mode.

**Comment by oleg-st** [comment] 2022-11-04 14:29
Done in 1.0.3

**Comment by owopeachy** [comment] 2022-11-04 14:32
thank you so much this is amazing

**Comment by oleg-st** [comment] 2022-11-04 19:14
@owopeachy Does it work as intended?

**Comment by owopeachy** [comment] 2022-11-04 19:54
works 100% yeah feels like native 1:1

**Comment by oleg-st** [comment] 2022-11-04 20:22
Good, I'll close the issue then.

**Closed by oleg-st** 2022-11-04 20:22 UTC
